### ISSUE TITLE
Map patch breaks map display

### ISSUE THREAD

**Issue by natecox** [samueldcorbin/achaea#1]
OS: macOS
Browser: Version 60.0.3088.3 (Official Build) dev (64-bit)

I just installed this suite of packages and noticed that the mapper seems to cease working properly with the map patch script enabled. The map gets stuck on a room I'm not currently in, and won't follow my character. Disabling the package returns the map to normal functionality.

**Comment by samueldcorbin** [comment]
Looks like Nexus switched to actually instantiating Map instead of using the Map object directly. I've updated the file and it should work now.
